### PR TITLE
fix(type-auth):isObject can not distinguish between object and array

### PR DESCRIPTION
**Pull request by hjzheng**

### CODE REVIEW

**Comment by kuitos** [comment]
Great job!

But what I prefer is to use the native api `Array.isArray` to check the array type rather than `Object.prototype.toString`, the old fashion way.
And, as a subtype of Object, `isObject([])` should also get a truthy assertion, giving a non-object judgement to array is not fair in my opinion.

see #6

**Comment by hjzheng** [comment]
In my opinion, in JavaScript array is a type like number and string. it is different from object. 
for your opinion, you can do it like this: `isObject([]) || isArray([])`.  

ps: 我们为什么要使用英文?

**Comment by kuitos** [comment]
I used to enumerate the definitions of array and object in any other languages, but as we are talking about javascript, I will give u the javascript-world reasons:
1. The only seven data types defined in the latest ECMAScript spec are `Undefined, Null, Boolean, String, Symbol, Number, and Object`(see [ecmascript-data-types-and-values](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-ecmascript-data-types-and-values)), so you treat Array as the same as string and number was unreasonable. 
2. Via the definition in ECMAScript spec (see [isArray](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-isarray)), the algorithm of `isArray` performs the first two steps:
   
   > 1. If Type(argument) is not Object, return false.
   > 2. If argument is an Array exotic object, return true.

from step one, we could realize that ECMAScript also treat Array as a subtype of Object in his deep inside, now your api told me `isObject(Array)` is not truthy, seriously?

Due to my fucking poor english writing, I would/could not expose my opinions any more, just all the above uh... Playing game is what I want to do now... 
so, that`s all..

**Comment by hjzheng** [comment]
OK，good reason.

**Comment by fengqiaojoe** [comment]
看了 lodash 中关于类型判定，你这个 isObject 与它的 [isObjectLike](https://lodash.com/docs/#isObjectLike) 一样， 它的 [isObject](https://lodash.com/docs/#isObject) 对对象的判断的定义是:

> Checks if value is the language type of Object. (e.g. arrays, functions, objects, regexes, new Number(0), and new String('')) 

它还有一个[isPlainObject](https://lodash.com/docs/#isPlainObject) 和 @hjzheng 认为的一样

**Comment by kuitos** [comment]
your words reminds me of my implementation that not perfect accorded with my opinion. 
see https://github.com/kuitos/angular-es-utils/commit/4fde18e1e5fbf1a7fd811c8858c53a85f1144554

**Pull request closed without merging**
